name: VillageDefense
main: pl.plajer.villagedefense.Main
authors: [TomTheDeveloper, Plajer, Tigerpanzer, montlikadani]
version: 4.5.0
softdepend: [HolographicDisplays, PlaceholderAPI, Parties, Spigot-Party-API-PAF, PartyAndFriends, MythicMobs]
api-version: 1.13

commands:
  VillageDefense:
    description: VillageDefense Commands
    usage: "\u00A76Correct usage: /vd [option]"
    aliases: [vd, villaged]
  VillageDefenseAdmin:
    description:
    usage: "\u00A76Correct usage: /vda [option]"
    aliases: [vda, villageadmin]
  vdmm:
    description: VillageDefense Commands
    usage: "\u00A76Correct usage: /vdmm [option]"
  vdmk:
    description: VillageDefense Commands
    usage: "\u00A76Correct usage: /vdmk [option]"

permissions:
  villagedefense.admin.*:
    default: op
    children:
      villagedefense.updatenotify: true
      villagedefense.admin: true
      villagedefense.admin.setup: true
      villagedefense.admin.setshopchest: true
      villagedefense.admin.setprice: true
      villagedefense.admin.create: true
      villagedefense.admin.delete: true
      villagedefense.admin.list: true
      villagedefense.admin.spychat: true
      villagedefense.admin.stopgame: true
      villagedefense.admin.forcestart: true
      villagedefense.admin.respawn: true
      villagedefense.admin.respawn.others: true
      villagedefense.admin.addsign: true
      villagedefense.admin.clear: true
      villagedefense.admin.addorbs: true
      villagedefense.admin.addorbs.others: true
      villagedefense.admin.setwave: true
      villagedefense.admin.sign.create: true
      villagedefense.admin.sign.break: true
      villagedefense.admin.reload: true
      villagedefense.command.override: true
      villagedefense.admin.setlevel: true
      villagedefense.admin.addlevel: true
      VillageDefemderMiSkYle.Admin: true